# Generated by Django 6.1.1 on 2026-09-26 10:27

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=255)),
                ('barcode_aktif', models.CharField(max_length=50, unique=True)),
                ('isi', models.IntegerField()),
                ('h_jual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_bad_stock', models.IntegerField()),
                ('qty_akhir', models.IntegerField()),
                ('qty_gd', models.IntegerField()),
                ('sat_k', models.CharField(blank=True, max_length=32)),
                ('sat_b', models.CharField(blank=True, max_length=32)),
                ('pareto', models.CharField(max_length=16)),
                ('jenis', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='VoidReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('VOID', 'VOID'), ('RETURN', 'RETURN')], max_length=6)),
                ('tanggal', models.DateField()),
                ('outlet', models.CharField(choices=[('BT1', 'BT1'), ('BT2', 'BT2'), ('BT3', 'BT3'), ('BT4', 'BT4'), ('BT5', 'BT5'), ('BT6', 'BT6'), ('BT7', 'BT7'), ('BT8', 'BT8'), ('BT9', 'BT9'), ('BT10', 'BT10'), ('BT11', 'BT11'), ('BT12', 'BT12'), ('BT13', 'BT13'), ('BT14', 'BT14'), ('BT15', 'BT15'), ('BT16', 'BT16'), ('BT17', 'BT17'), ('BT18', 'BT18'), ('BT19', 'BT19'), ('BT20', 'BT20'), ('BT21', 'BT21'), ('BT22', 'BT22'), ('BT23', 'BT23'), ('BT24', 'BT24'), ('BT25', 'BT25'), ('BT26', 'BT26'), ('BT27', 'BT27')], max_length=4)),
                ('nama_kasir', models.CharField(max_length=100)),
                ('otoritas', models.CharField(max_length=100, verbose_name='Otoritas/MOD')),
                ('no_trans', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Trans')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('harga_jual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='H. Jual')),
                ('alasan', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='foto/%Y/%m/', validators=[inventory.models.validasi_foto])),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='inventory.barang')),
            ],
            options={
                'verbose_name': 'Transaksi Void/Return',
                'verbose_name_plural': 'Transaksi Void/Return',
                'ordering': ['-tanggal', '-id'],
                'indexes': [models.Index(fields=['jenis', 'tanggal'], name='voidreturn_jenis_tanggal_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='voidreturn_qty_min_1'), models.CheckConstraint(condition=models.Q(('jenis__in', ['VOID', 'RETURN'])), name='voidreturn_jenis_valid'), models.CheckConstraint(condition=models.Q(('outlet__in', ['BT1', 'BT2', 'BT3', 'BT4', 'BT5', 'BT6', 'BT7', 'BT8', 'BT9', 'BT10', 'BT11', 'BT12', 'BT13', 'BT14', 'BT15', 'BT16', 'BT17', 'BT18', 'BT19', 'BT20', 'BT21', 'BT22', 'BT23', 'BT24', 'BT25', 'BT26', 'BT27'])), name='voidreturn_outlet_valid'), models.CheckConstraint(condition=models.Q(models.Q(('jenis', 'RETURN'), _negated=True), ('harga_jual__isnull', False), _connector='OR'), name='voidreturn_return_harga_wajib'), models.CheckConstraint(condition=models.Q(('jenis', 'VOID'), models.Q(('no_trans__isnull', True), ('no_trans', ''), _connector='OR'), ('harga_jual__isnull', True)), name='voidreturn_void_kosong'), models.CheckConstraint(condition=models.Q(('foto', ''), _negated=True), name='voidreturn_foto_wajib')],
            },
        ),
    ]
