# Generated by Django 6.1.1 on 2026-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voidreturn',
            name='voidreturn_void_kosong',
        ),
        migrations.AlterField(
            model_name='barang',
            name='barcode_aktif',
            field=models.CharField(max_length=50, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='h_jual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga Jual'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='isi',
            field=models.IntegerField(verbose_name='Isi'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(max_length=32, verbose_name='Jenis Barang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Nama Barang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='pareto',
            field=models.CharField(max_length=16, verbose_name='Pareto'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='qty_akhir',
            field=models.IntegerField(verbose_name='Qty Akhir'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='qty_bad_stock',
            field=models.IntegerField(verbose_name='Qty Bad Stock'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='qty_gd',
            field=models.IntegerField(verbose_name='Qty Gudang'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='sat_b',
            field=models.CharField(blank=True, max_length=32, verbose_name='Satuan Besar'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='sat_k',
            field=models.CharField(blank=True, max_length=32, verbose_name='Satuan Kecil'),
        ),
        migrations.AlterField(
            model_name='voidreturn',
            name='harga_jual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga Jual'),
        ),
        migrations.AlterField(
            model_name='voidreturn',
            name='no_trans',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No Transaksi'),
        ),
        migrations.AddConstraint(
            model_name='voidreturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('jenis', 'VOID'), _negated=True), models.Q(models.Q(('no_trans__isnull', True), ('no_trans', ''), _connector='OR'), ('harga_jual__isnull', True)), _connector='OR'), name='voidreturn_void_kosong'),
        ),
    ]
